import type { DealershipSettings, DispatchRepairOrder, User } from '../types';

export const PREVIEW_USER: User = {
  uid: 'preview-user',
  email: 'preview@local.dev',
  username: 'Preview User',
  role: 'admin',
  approved: true,
  status: 'approved',
  jobTitle: 'Service Manager',
  dealershipId: 'hyundai',
  tenantId: 'hyundai',
  department: 'service',
};

function yesterday(): string {
  const d = new Date();
  d.setDate(d.getDate() - 1);
  return d.toLocaleDateString('en-CA');
}

export function buildPreviewDispatchOrders(
  dealershipId: string,
  currentDate: string
): DispatchRepairOrder[] {
  const now = new Date().toISOString();
  const prior = yesterday();
  const base = { dealershipId, isCompleted: false, lastUpdated: now };

  return [
    {
      ...base,
      id: 'preview-queue-1',
      roNumber: '884201',
      techNumber: '402',
      tagNumber: 'A-12',
      customerLastName: 'MARTINEZ',
      customerName: 'Maria Martinez',
      phoneNumber: '(805) 555-0142',
      vinLastEight: 'G2054992',
      department: 'unassigned',
      currentLaneId: 'unassigned',
      lifecycleStatus: 'active',
      status: 'WIP',
      isWaiting: true,
      isPdl: false,
      dateCreated: currentDate,
      model: 'Tucson',
      year: '2024',
    },
    {
      ...base,
      id: 'preview-lube-1',
      roNumber: '884198',
      techNumber: '118',
      tagNumber: 'B-07',
      customerLastName: 'CHEN',
      customerName: 'James Chen',
      phoneNumber: '(805) 555-0198',
      department: 'lube',
      currentLaneId: 'lube',
      lifecycleStatus: 'active',
      status: 'WIP',
      isWaiting: false,
      isPdl: true,
      dateCreated: currentDate,
      model: 'Santa Fe',
      year: '2023',
    },
    {
      ...base,
      id: 'preview-quick-1',
      roNumber: '884175',
      techNumber: '205',
      tagNumber: 'C-22',
      customerLastName: 'WILLIAMS',
      customerName: 'Dana Williams',
      department: 'quick_service',
      currentLaneId: 'quick_service',
      lifecycleStatus: 'active',
      status: 'POO',
      dateCreated: currentDate,
      model: 'Elantra',
      year: '2022',
    },
    {
      ...base,
      id: 'preview-ac-1',
      roNumber: '884160',
      techNumber: '331',
      tagNumber: 'D-09',
      customerLastName: 'GARCIA',
      customerName: 'Luis Garcia',
      department: 'ac_electrical',
      currentLaneId: 'ac_electrical',
      lifecycleStatus: 'active',
      status: 'WFA',
      dateCreated: currentDate,
      model: 'Palisade',
      year: '2025',
    },
    {
      ...base,
      id: 'preview-drive-1',
      roNumber: '884142',
      techNumber: '402',
      tagNumber: 'E-31',
      customerLastName: 'NGUYEN',
      customerName: 'Kim Nguyen',
      department: 'drivability',
      currentLaneId: 'drivability',
      lifecycleStatus: 'active',
      status: 'WIP',
      dateCreated: currentDate,
      model: 'Kona',
      year: '2021',
    },
    {
      ...base,
      id: 'preview-heavy-1',
      roNumber: '884130',
      techNumber: '512',
      tagNumber: 'F-04',
      customerLastName: 'BROWN',
      customerName: 'Robert Brown',
      department: 'heavyline',
      currentLaneId: 'heavyline',
      lifecycleStatus: 'active',
      status: 'WIP',
      dateCreated: currentDate,
      model: 'Sonata',
      year: '2020',
    },
    {
      ...base,
      id: 'preview-diesel-1',
      roNumber: '884118',
      techNumber: '601',
      tagNumber: 'G-18',
      customerLastName: 'DAVIS',
      customerName: 'Pat Davis',
      department: 'diesel',
      currentLaneId: 'diesel',
      lifecycleStatus: 'active',
      status: 'POO',
      dateCreated: currentDate,
    },
    {
      ...base,
      id: 'preview-trans-1',
      roNumber: '884105',
      techNumber: '702',
      tagNumber: 'H-02',
      customerLastName: 'LEE',
      customerName: 'Sam Lee',
      department: 'trans',
      currentLaneId: 'trans',
      lifecycleStatus: 'active',
      status: 'WFA',
      dateCreated: currentDate,
    },
    {
      ...base,
      id: 'preview-down-1',
      roNumber: '883990',
      techNumber: '402',
      tagNumber: 'Z-11',
      customerLastName: 'TAYLOR',
      customerName: 'Chris Taylor',
      department: 'down_in_shop',
      currentLaneId: 'down_in_shop',
      lifecycleStatus: 'overnight',
      status: 'WIP',
      dateCreated: prior,
      model: 'Ioniq 5',
      year: '2024',
    },
    {
      ...base,
      id: 'preview-carry-1',
      roNumber: '883978',
      techNumber: '118',
      tagNumber: 'Y-08',
      customerLastName: 'HILL',
      customerName: 'Jordan Hill',
      department: 'lube',
      currentLaneId: 'lube',
      lifecycleStatus: 'active',
      status: 'WIP',
      dateCreated: prior,
      model: 'Venue',
      year: '2023',
    },
  ];
}

export const PREVIEW_DEALERSHIP_SETTINGS: Partial<DealershipSettings> = {
  enableDispatchTab: true,
  dispatchShowTodayLoad: true,
  dispatchBlockWhenFull: false,
  appointmentTarget: 24,
};
